# Note: Remove the baseurl in order to deploy at the domain root
baseurl: /tufte-test
title: Commonplace Book
# Whether the header (with large title and subtitle) should be displayed
header: false
subtitle: An attempts a publishing my working notes of theology and assundries
author: Keelan Cook
description: A working journal of unfinished and developing notes.
show_author: true
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
# permalink: /blog/:categories/:year/:month/:day/:title.html
permalink: /blog/:categories/:slug
timezone: America/New_York
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
plugins:
  - jekyll-feed
